CREATE OR REPLACE VIEW SALES.PUBLIC.QUANTITY_BY_PRODUCT_VIEW(
    PRODUCT,
    REVENUE
) AS
SELECT
    PRODUCT,
    SUM(QuantityOrdered) AS Quantity
FROM SALES.PUBLIC.order_raw
GROUP BY
    PRODUCT;

SELECT * FROM SALES.PUBLIC.QUANTITY_BY_PRODUCT_VIEW;
