CREATE OR REPLACE VIEW SALES.PUBLIC.REVENUE_PER_MONTH_VIEW(
    ORDERMONTH,
    REVENUE
) AS
SELECT
    DATE_TRUNC('month', TO_TIMESTAMP(OrderDate, 'MM/DD/YY HH24:MI')) AS OrderMonth,
    SUM(QuantityOrdered * PriceEach) AS Revenue
FROM SALES.PUBLIC.order_raw
GROUP BY
    DATE_TRUNC('month', TO_TIMESTAMP(OrderDate, 'MM/DD/YY HH24:MI'));

SELECT * FROM SALES.PUBLIC.REVENUE_PER_MONTH_VIEW;
